package observability

import (
	"fmt"
	"io"
	"sort"
	"sync"
	"time"

	"github.com/factory-demo/portfolio-api/internal/domain"
)

type Metrics struct {
	mu       sync.Mutex
	requests map[string]uint64
	count    uint64
	seconds  float64
	insights map[string]uint64
}

func NewMetrics() *Metrics {
	return &Metrics{
		requests: map[string]uint64{
			"200": 0,
			"400": 0,
			"404": 0,
			"502": 0,
		},
		// Pre-seeding exactly the two approved insight types keeps the family
		// bounded: ObserveInsights only ever writes to these keys, so no
		// request-derived value can create a new series.
		insights: map[string]uint64{
			string(domain.InsightConcentration): 0,
			string(domain.InsightCashBuffer):    0,
		},
	}
}

func (m *Metrics) Observe(status int, duration time.Duration) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.requests[fmt.Sprintf("%d", status)]++
	m.count++
	m.seconds += duration.Seconds()
}

// ObserveInsights increments the insight counter once per generated insight,
// keyed by type. Any insight whose type is not one of the two pre-seeded
// constants is ignored, so the family can never gain an unbounded or
// request-derived dimension.
func (m *Metrics) ObserveInsights(insights []domain.Insight) {
	m.mu.Lock()
	defer m.mu.Unlock()
	for _, insight := range insights {
		if _, ok := m.insights[string(insight.Type)]; ok {
			m.insights[string(insight.Type)]++
		}
	}
}

func (m *Metrics) WritePrometheus(writer io.Writer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	_, _ = fmt.Fprintln(writer, "# HELP portfolio_http_requests_total Total portfolio API requests.")
	_, _ = fmt.Fprintln(writer, "# TYPE portfolio_http_requests_total counter")
	statuses := make([]string, 0, len(m.requests))
	for status := range m.requests {
		statuses = append(statuses, status)
	}
	sort.Strings(statuses)
	for _, status := range statuses {
		_, _ = fmt.Fprintf(writer, "portfolio_http_requests_total{method=\"GET\",route=\"/api/v1/customers/{customerId}/portfolio\",status=\"%s\"} %d\n", status, m.requests[status])
	}

	_, _ = fmt.Fprintln(writer, "# HELP portfolio_http_request_duration_seconds Portfolio API request duration.")
	_, _ = fmt.Fprintln(writer, "# TYPE portfolio_http_request_duration_seconds summary")
	_, _ = fmt.Fprintf(writer, "portfolio_http_request_duration_seconds_sum %g\n", m.seconds)
	_, _ = fmt.Fprintf(writer, "portfolio_http_request_duration_seconds_count %d\n", m.count)

	_, _ = fmt.Fprintln(writer, "# HELP portfolio_insights_generated_total Portfolio insights generated by type.")
	_, _ = fmt.Fprintln(writer, "# TYPE portfolio_insights_generated_total counter")
	types := make([]string, 0, len(m.insights))
	for insightType := range m.insights {
		types = append(types, insightType)
	}
	sort.Strings(types)
	for _, insightType := range types {
		_, _ = fmt.Fprintf(writer, "portfolio_insights_generated_total{type=\"%s\"} %d\n", insightType, m.insights[insightType])
	}
}
